const nodemailer = require('nodemailer');
const PDFDocument = require('pdfkit');
const { PassThrough } = require('stream');

/**
 * Service to handle Email and PDF generation for contractor assignments
 */
const sendAssignmentEmail = async (data) => {
    const { report, contractor, milestones, estimatedCost, additionalNotes } = data;

    // 1. Create a transporter (using a dummy ethereal account for dev, or env vars)
    // For the hackathon, we'll use a placeholder logic that can be easily updated.
    const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST || 'smtp.ethereal.email',
        port: process.env.SMTP_PORT || 587,
        auth: {
            user: process.env.SMTP_USER || 'placeholder@ethereal.email',
            pass: process.env.SMTP_PASS || 'placeholder_pass'
        }
    });

    // 2. Generate PDF in memory
    const doc = new PDFDocument();
    const buffers = [];
    doc.on('data', buffers.push.bind(buffers));

    return new Promise((resolve, reject) => {
        doc.on('end', async () => {
            const pdfData = Buffer.concat(buffers);

            try {
                // 3. Send Email
                const info = await transporter.sendMail({
                    from: '"Smart City Admin" <admin@smartcity.gov>',
                    to: contractor.email,
                    subject: `New Assignment: ${report.category} #${report.id}`,
                    text: `Hello ${contractor.full_name},\n\nYou have been assigned a new infrastructure mission: ${report.category}.\n\nEstimated Cost: $${estimatedCost}\n\nPlease find the detailed assignment PDF attached.\n\nBest regards,\nSmart City Management`,
                    attachments: [
                        {
                            filename: `Assignment_Report_${report.id}.pdf`,
                            content: pdfData
                        }
                    ]
                });

                console.log('✅ Email sent: %s', info.messageId);
                resolve(info);
            } catch (err) {
                console.error('❌ Email failed:', err);
                reject(err);
            }
        });

        // PDF Content
        doc.fontSize(20).text('OFFICIAL WORK ASSIGNMENT', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Date: ${new Date().toLocaleDateString()}`);
        doc.text(`Contractor: ${contractor.full_name}`);
        doc.text(`Email: ${contractor.email}`);
        doc.moveDown();

        doc.fontSize(14).text('ISSUE DETAILS', { underline: true });
        doc.fontSize(12).text(`Category: ${report.category}`);
        doc.text(`Location: ${report.latitude}, ${report.longitude}`);
        doc.text(`Description: ${report.description}`);
        doc.moveDown();

        doc.fontSize(14).text('EXECUTION PLAN & MILESTONES', { underline: true });
        doc.fontSize(12).text(`Estimated Total Cost: $${estimatedCost}`);
        doc.moveDown();

        milestones.forEach((m, idx) => {
            doc.text(`${idx + 1}. ${m.title}: ${m.description}`);
        });

        if (additionalNotes) {
            doc.moveDown();
            doc.fontSize(14).text('ADDITIONAL NOTES', { underline: true });
            doc.fontSize(12).text(additionalNotes);
        }

        doc.moveDown(2);
        doc.fontSize(10).text('This is an automated document generated by the Smart City Infrastructure Command Center.', { align: 'center', color: 'grey' });

        doc.end();
    });
};

module.exports = {
    sendAssignmentEmail
};
